# Taplo configuration for TOML file formatting
# See https://taplo.tamasfe.dev/configuration/ for more options

[formatting]
# Align entries in tables
align_entries = true

# Auto-expand arrays that exceed the column width
array_auto_expand = true

# Maximum line width
column_width = 80

# Use 4 spaces for indentation
indent_string = "    "

# Respect .gitignore when finding files
include_ignored = false

# Additional formatting options
align_comments = true
array_trailing_comma = true
compact_entries = false
compact_arrays = false
