blank_issues_enabled: false
contact_links:
  - name: "GitHub Community Support"
    url: "https://github.com/smorin/py-launch-blueprint/blob/main/CONTRIBUTING.md"
    about: "Please ask and answer questions here."
