blank_issues_enabled: false
contact_links:
  - name: "📖 Contribution Guide"
    url: "https://github.com/smorin/py-launch-blueprint/blob/main/CONTRIBUTING.md"
    about: "Please read our contribution guide before submitting an issue"
