blank_issues_enabled: false
contact_links:
  - name: "💬 Questions & Discussions"
    url: "https://github.com/smorin/py-launch-blueprint/discussions"
    about: "Ask questions and discuss with other community members."
