name: "❓ Question / Support"
description: "Ask a question or request support."
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: "## ❓ Question / Support\nPlease provide details about your question or issue."
  - type: textarea
    id: question
    attributes:
      label: "Your Question"
      description: "What do you need help with?"
    validations:
      required: true
