name: Generate Changelog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install cogapp

    - name: Generate Changelog
      run: |
        . venv/bin/activate
        cog changelog.md
        git add changelog.md
        git commit -m "chore: update changelog"
        git push
