name: CLA Verification

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cla-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: CLA Assistant
      uses: cla-assistant/github-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        cla-url: https://cla-assistant.io/py_launch_blueprint
        name: CLA Check



  check-cla:
    runs-on: ubuntu-latest
    steps:
      - name: Check if CLA is signed
        uses: cla-assistant/github-action@v1
        with:
          path-to-signatures: ".github/cla-signatures.json"
          path-to-document: "cla/cla-individual.md"
