name: Update Contributors

on:
  push:
    branches:
          #[ main ] will back revert to the main branch after the PR is tested
          - bug/update-directory-update-contributors
  pull_request:
    branches:
        #[ main ] will back revert to the main branch after the PR is tested
          - bug/update-directory-update-contributors
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: bug/update-directory-update-contributors

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: List files in root
        run: ls -R .

      - name: List files in scripts directory
        run: ls -R scripts/

      - name: Update CONTRIBUTORS.md
        run: |
          python scripts/update_contributors.py

      - name: Ensure on a branch
        run: |
          git checkout -B update-contributors
          git push origin update-contributors

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: update contributors list'
          title: 'chore: update contributors list'
          body: 'Automatically updated contributors list using Git log'
          branch: update-contributors
          base: main  # Use the main branch as the base
          delete-branch: true
