name: Update Contributors

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Debug workflow environment
        run: |
          ls -la
          pwd
          git status
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"

      - name: Update CONTRIBUTORS.md
        run: |
          python $GITHUB_WORKSPACE/update_contributors.py || echo "Failed to update contributors, continuing anyway"
        continue-on-error: true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: update contributors list'
          title: 'chore: update contributors list'
          body: 'Automatically updated contributors list using Git log'
          branch: update-contributors
          delete-branch: true
