name: Update Contributors

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Update CONTRIBUTORS.md
        run: |
          # Get list of contributors
          git log --format='%aN <%aE>' | sort -u > temp_contributors
          
          # Update CONTRIBUTORS.md
          awk '
            BEGIN { p=1 }
            /<!-- COG-CONTRIBUTORS-LIST:START -->/ {
              print;
              system("cat temp_contributors");
              print "<!-- COG-CONTRIBUTORS-LIST:END -->";
              p=0;
              next;
            }
            /<!-- COG-CONTRIBUTORS-LIST:END -->/ { p=1; next }
            p { print }
          ' CONTRIBUTORS.md > CONTRIBUTORS.md.new
          
          # Replace old file with new one
          mv CONTRIBUTORS.md.new CONTRIBUTORS.md
          rm temp_contributors

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: update contributors list'
          title: 'chore: update contributors list'
          body: 'Automatically updated contributors list using git log'
          branch: update-contributors
          delete-branch: true
